### ISSUE TITLE
Move composer & npm install from Makefile to DDEV hooks

### ISSUE THREAD

**Issue by johndwells** [onedarnleyroad/craftcms#48]
Add this to `.ddev/config.yaml`:

```
hooks:
  post-start:
    - exec: composer install
    - exec: npm install
```

And then our Makefile `up` command only needs to concern itself with DDEV.
